### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by ebym** [minanagehsalalma/huawei-dg8045-hg630-hg633-Config-file-decryption-and-password-decode#2]
I'm trying to decrypt configuration downloaded from HG633-12, HW Rev. A. I even tried CyberChef with Key, IV values mentioned in python file. with and without CBC padding. It isn't decrypting, any help in decrypting this is appreciated.

`$ python hg633.py decrypt downloadconfigfile.conf hu`
 ```
 File "hg633.py", line 77
    realdata = f'"{data1}"'
                          ^
SyntaxError: invalid syntax
```

**Comment by minanagehsalalma** [comment]
it been two years , so i don't remember much, i don't get this error tho 

can you try this instead?

`realdata = f'{data1}'
`

or just send over the file.

**Comment by ebym** [comment]
`realdata = f'{data1}' ` is throwing same error.

Do i send the config file ?.

Thanks.

**Comment by minanagehsalalma** [comment]
Yes

**Comment by ebym** [comment]
Attached.

[hg633.conf.txt](https://github.com/minanagehsalalma/huawei-dg8045-hg630-hg633-Config-file-decryption-and-password-decode/files/13188369/hg633.conf.txt)

Thanks.

**Comment by minanagehsalalma** [comment]
@ebym idk exactly what's going on but i seem to have problems running python 

```
from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'
```

and it's already installed !

**Comment by ebym** [comment]
@minanagehsalalma - i'm running Python 2.7.18.

I came across another script without `def repl(blahblah):` section. Even tried using Key & IV values from your file, with the same following results.

```
"Decrypting..."
"Bad config file...exiting"
```

**Comment by minanagehsalalma** [comment]
@ebym for my script use python 3.6 

```
"Decrypting..."
"Bad config file...exiting"
```
just remove the sys.exit from the code.

**Comment by ebym** [comment]
your file have one ref to `sys.exit`, whilst the other script have five ref to the same.

other script leads to multiple issues with `sys.exit` removed from decrypt section.

attached is the other script for your reference.

[huawei-hg633.py.txt](https://github.com/minanagehsalalma/huawei-dg8045-hg630-hg633-Config-file-decryption-and-password-decode/files/13202253/huawei-hg633.py.txt)

**Comment by ebym** [comment]
$ python -V
Python 3.6.5

Following is the error with and without `sys.exit` in the script. The errors are the same with python 3.7, 3.8 & 3.9.

$ python3 hg633.py decrypt Downloads/hg633.conf hu
```
Decrypting...
Bad config file...exiting
Traceback (most recent call last):
  File "hg633.py", line 198, in <module>
    main()
  File "hg633.py", line 192, in main
    decrypt_config(input_file, output_file) 
  File "hg633.py", line 116, in decrypt_config
    actual_md5_hash = calc_actual_md5_hash(config_text)
  File "hg633.py", line 95, in calc_actual_md5_hash
    md5.update(enc_config_body)
  File "/usr/lib/python3/dist-packages/Crypto/Hash/hashalgo.py", line 69, in update
    return self._hash.update(data)
TypeError: Unicode-objects must be encoded before hashing

```

**Comment by minanagehsalalma** [comment]
Closing this because the reported script/runtime failure is fixed on main in 36e3b55. If someone later extracts confirmed HG633-12 backup constants or format details, that should be tracked as a new variant-support issue rather than reopening the old Python error report.

**Comment by minanagehsalalma** [comment]
Tested this again against the exact attachment in this issue.

What is fixed on `main` now:
- the old Python 3 crash path is gone
- the repo now uses a unified `huawei_tool.py` entrypoint
- dependency/setup is documented via `requirements.txt`
- invalid inputs fail with a clear error instead of falling through into `TypeError` / `SyntaxError` noise

What I verified locally:
- the legacy `hg633.py` still reproduces the issue's Python 3 follow-on crash after `Bad config file...exiting`
- the current code on `main` no longer crashes on that path
- the attached `hg633.conf.txt` still does not decrypt with the known HG633 constants from this repo or with the alternate `huawei-hg633.py` constants shared in the thread

So the original script/runtime issue is resolved, but this specific HG633-12 backup appears to be a different unsupported variant or format, not just the same Python bug. That would need separate key or format extraction from the matching firmware before this repo can decrypt it.

Fixed in commit: `36e3b55`
